const BOOKING_WORKFLOW_STATES = Object.freeze({
  REQUEST_SUBMITTED: "REQUEST_SUBMITTED",
  ADMIN_REVIEW: "ADMIN_REVIEW",
  CONSULTATION_SCHEDULED: "CONSULTATION_SCHEDULED",
  CONSULTATION_COMPLETED: "CONSULTATION_COMPLETED",
  QUOTE_GENERATED: "QUOTE_GENERATED",
  QUOTE_ACCEPTED: "QUOTE_ACCEPTED",
  AGREEMENT_GENERATED: "AGREEMENT_GENERATED",
  EVENT_SCHEDULED: "EVENT_SCHEDULED",
  EVENT_IN_PROGRESS: "EVENT_IN_PROGRESS",
  EVENT_COMPLETED: "EVENT_COMPLETED",
});

const BOOKING_WORKFLOW_SEQUENCE = Object.freeze([
  BOOKING_WORKFLOW_STATES.REQUEST_SUBMITTED,
  BOOKING_WORKFLOW_STATES.ADMIN_REVIEW,
  BOOKING_WORKFLOW_STATES.CONSULTATION_SCHEDULED,
  BOOKING_WORKFLOW_STATES.CONSULTATION_COMPLETED,
  BOOKING_WORKFLOW_STATES.QUOTE_GENERATED,
  BOOKING_WORKFLOW_STATES.QUOTE_ACCEPTED,
  BOOKING_WORKFLOW_STATES.AGREEMENT_GENERATED,
  BOOKING_WORKFLOW_STATES.EVENT_SCHEDULED,
  BOOKING_WORKFLOW_STATES.EVENT_IN_PROGRESS,
  BOOKING_WORKFLOW_STATES.EVENT_COMPLETED,
]);

const BOOKING_WORKFLOW_LABELS = Object.freeze({
  REQUEST_SUBMITTED: "Request Submitted",
  ADMIN_REVIEW: "Admin Review",
  CONSULTATION_SCHEDULED: "Consultation Scheduled",
  CONSULTATION_COMPLETED: "Consultation Completed",
  QUOTE_GENERATED: "Quote Generated",
  QUOTE_ACCEPTED: "Quote Accepted",
  AGREEMENT_GENERATED: "Agreement Generated",
  EVENT_SCHEDULED: "Event Scheduled",
  EVENT_IN_PROGRESS: "Event In Progress",
  EVENT_COMPLETED: "Event Completed",
});

module.exports = {
  BOOKING_WORKFLOW_STATES,
  BOOKING_WORKFLOW_SEQUENCE,
  BOOKING_WORKFLOW_LABELS,
};
